version: "3"
services:
  client:
    container_name: client
    build: ./client
    image: web-client
    stdin_open: true
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - api
    volumes:
      - ./client:/client
      - /client/node_modules
    networks:
      - bah-network
  api:
    container_name: api
    build: ./api
    image: web-api
    restart: always
    ports:
      - 3000:3000
    env_file:
      - api.env
      - db.env
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - psql
    networks:
      - bah-network
  psql:
    container_name: psql
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - db.env
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./scripts:/docker-entrypoint-initdb.d/
    networks:
      - bah-network
volumes:
  database-data:
networks:
  bah-network: