version: 2.1
orbs: circleci/heroku@0.0.10
jobs:
  deploy-to-heroku:
    docker:
      - image: 'circleci/node:10.0'
    steps:
      - checkout
      - echo 'HELLO WORLD'
      # - heroku/install
      # - setup_remote_docker:
      #   version: 19.03.8
      # - run:
      #   name: Build image
      #   command:
workflows:
  version: 2
  deploy:
    jobs:
      - deploy-to-heroku:
        filters:
          branches:
            only:
              - master