version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  run_tests:
    docker:
      - image: 'circleci/node:10.0'
    steps:
      - checkout
      - run: echo 'This will eventually run tests'
  build_and_deploy:
    docker:
      - image: 'circleci/node:10.0'
    steps:
      - checkout
      - run: echo 'This will build and deploy to heroku'
workflows:
  version: 2
  deploy_to_heroku:
    jobs:
      - run_tests
      - build_and_deploy:
          requires:
            - run_tests
          filters:
            branches:
              only:
                - master