version: 2.1
jobs:
  run_tests:
    docker:
      - image: 'circleci/node:10.0'
    steps:
      - checkout
      - run:
          name: Run Tests
          command: echo 'This will eventually run tests'
  build_and_deploy:
    docker:
      - image: 'circleci/node:10.0'
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.8
      - run:
          name: Build Docker image and push to Heroku registry
          command: >
            docker login --username=$HEROKU_USERNAME --password=$HEROKU_PASSWORD registry.heroku.com

            docker build --rm=false -t registry.heroku.com/boardathome/web .

            docker push registry.heroku.com/boardathome/web:latest
workflows:
  version: 2
  deploy_to_heroku:
    jobs:
      - run_tests
      - build_and_deploy:
          requires:
            - run_tests
          filters:
            branches:
              only:
                - master