version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  run_tests:
    docker:
      - image: 'circleci/node:10.0'
    steps:
      - checkout
      - run:
          name: Run Tests
          command: echo 'This will eventually run tests'
  build_and_deploy:
    docker:
      - image: 'circleci/node:10.0'
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker:
          version: 19.03.8
      - run:
          name: Build Docker image and push to Heroku registry
          command: >
            HEROKU_API_KEY=$HEROKU_PASSWORD heroku container:login

            HEROKU_API_KEY=$HEROKU_PASSWORD heroku container:push -a boardathome web

            HEROKU_API_KEY=$HEROKU_PASSWORD heroku container:release -a boardathome web
workflows:
  version: 2
  deploy_to_heroku:
    jobs:
      - run_tests
      - build_and_deploy:
          requires:
            - run_tests
          filters:
            branches:
              only:
                - master